#!/usr/bin/with-contenv bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
if [[ "${OTBR_WEB:-1}" == "0" ]]; then
    echo "INFO: Skipping otbr-web, disabled..."
    exec s6-pause
fi

echo "INFO: Starting otbr-web..."

otbr_web_args=(
    "-I" "wpan0"
    "-d6" "-s"
    "-p" "${OTBR_WEB_PORT:-8080}"
    "-a" "${OTBR_WEB_INTERFACE:-::}"
)

exec stdbuf -oL /usr/sbin/otbr-web "${otbr_web_args[@]}"
