#!/usr/bin/with-contenv bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
if [ "${OTBR_WEB:-1}" != "0" ]; then
    echo "INFO: Starting otbr-web..."
    declare otbr_web_port

    otbr_web_port="${OTBR_WEB_PORT:-8080}"
    otbr_web_args=("-I" "wpan0" "-d6" "-s" "-p" "${otbr_web_port}")

    if [ -n "${OTBR_WEB_ADDRESS}" ]; then
        otbr_web_args+=("-a" "${OTBR_WEB_ADDRESS}")
    fi

    if [ -n "${OTBR_WEB_INTERFACE}" ]; then
        otbr_web_args+=("-a" "${OTBR_WEB_INTERFACE}")
    else
        # Default to listening on all interfaces
        otbr_web_args+=("-a" "::")
    fi

    exec stdbuf -oL /usr/sbin/otbr-web "${otbr_web_args[@]}"
else
    echo "INFO: Skipping otbr-web, disabled..."
    exec s6-pause
fi
